### ISSUE TITLE
dkms file

### ISSUE THREAD

**Issue by orestisgorgas** [codeworkx/rtl8812au_asus#4]
Hi! First of all great job with the driver!

 I tried to make a build it with dkms and I added the following dkms.conf file:

```
 PACKAGE_NAME="8812au" 
 PACKAGE_VERSION="1.0" 
 CLEAN="make clean" 
  MAKE[0]="make all" 
  BUILT_MODULE_NAME[0]="8812au"
  BUILT_MODULE_LOCATION[0]="./"
 DEST_MODULE_LOCATION[0]="/kernel/updates/dkms"
  AUTOINSTALL="yes"
```

However, I get a "No rule to make target `all'" error. I see that there is an "all" target. Is there any particular change needed? Is it possible to add in the repository a dkms.conf file for automatic updates?

**Comment by codeworkx** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/?h=rtl8812au_asus-dkms
https://aur.archlinux.org/cgit/aur.git/tree/dkms.conf?h=rtl8812au_asus-dkms
